name: yifeng_site
description: "A new Flutter project."
publish_to: 'none'

version: 1.2.7+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  url_launcher: ^6.3.0
  path_provider: ^2.1.4
  image_gallery_saver_plus: ^4.0.1
  permission_handler: ^11.3.1
  fluttertoast: ^8.2.8
  intl: ^0.19.0
  lunar: ^1.7.0
  shared_preferences: ^2.3.2
  geolocator: ^13.0.1
  quick_actions: ^1.1.0
  webview_flutter: ^4.4.2
  share_plus: ^10.1.4
  device_preview: ^1.2.0
  device_preview_screenshot: ^1.0.0
  clay_containers: ^0.3.4
  flutter_colorpicker: ^1.0.3
  image_picker: ^1.1.2
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/app.png"


flutter:
  uses-material-design: true
  assets:
    - assets/icon/app.png
    - assets/images/